// source: signaling.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.signaling.v1.Error', null, global);
goog.exportSymbol('proto.signaling.v1.IceCandidate', null, global);
goog.exportSymbol('proto.signaling.v1.Identity', null, global);
goog.exportSymbol('proto.signaling.v1.SdpExchange', null, global);
goog.exportSymbol('proto.signaling.v1.SdpExchange.Type', null, global);
goog.exportSymbol('proto.signaling.v1.SignalRequest', null, global);
goog.exportSymbol('proto.signaling.v1.SignalRequest.PayloadCase', null, global);
goog.exportSymbol('proto.signaling.v1.SignalResponse', null, global);
goog.exportSymbol('proto.signaling.v1.SignalResponse.PayloadCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.v1.SignalRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.signaling.v1.SignalRequest.oneofGroups_);
};
goog.inherits(proto.signaling.v1.SignalRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.v1.SignalRequest.displayName = 'proto.signaling.v1.SignalRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.v1.SignalResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.signaling.v1.SignalResponse.oneofGroups_);
};
goog.inherits(proto.signaling.v1.SignalResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.v1.SignalResponse.displayName = 'proto.signaling.v1.SignalResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.v1.Identity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.signaling.v1.Identity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.v1.Identity.displayName = 'proto.signaling.v1.Identity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.v1.SdpExchange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.signaling.v1.SdpExchange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.v1.SdpExchange.displayName = 'proto.signaling.v1.SdpExchange';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.v1.IceCandidate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.signaling.v1.IceCandidate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.v1.IceCandidate.displayName = 'proto.signaling.v1.IceCandidate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.v1.Error = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.signaling.v1.Error, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.v1.Error.displayName = 'proto.signaling.v1.Error';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.signaling.v1.SignalRequest.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.signaling.v1.SignalRequest.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  REGISTRATION: 1,
  SDP: 2,
  ICE: 3
};

/**
 * @return {proto.signaling.v1.SignalRequest.PayloadCase}
 */
proto.signaling.v1.SignalRequest.prototype.getPayloadCase = function() {
  return /** @type {proto.signaling.v1.SignalRequest.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.signaling.v1.SignalRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.v1.SignalRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.v1.SignalRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.v1.SignalRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.SignalRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    registration: (f = msg.getRegistration()) && proto.signaling.v1.Identity.toObject(includeInstance, f),
    sdp: (f = msg.getSdp()) && proto.signaling.v1.SdpExchange.toObject(includeInstance, f),
    ice: (f = msg.getIce()) && proto.signaling.v1.IceCandidate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.v1.SignalRequest}
 */
proto.signaling.v1.SignalRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.v1.SignalRequest;
  return proto.signaling.v1.SignalRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.v1.SignalRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.v1.SignalRequest}
 */
proto.signaling.v1.SignalRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.signaling.v1.Identity;
      reader.readMessage(value,proto.signaling.v1.Identity.deserializeBinaryFromReader);
      msg.setRegistration(value);
      break;
    case 2:
      var value = new proto.signaling.v1.SdpExchange;
      reader.readMessage(value,proto.signaling.v1.SdpExchange.deserializeBinaryFromReader);
      msg.setSdp(value);
      break;
    case 3:
      var value = new proto.signaling.v1.IceCandidate;
      reader.readMessage(value,proto.signaling.v1.IceCandidate.deserializeBinaryFromReader);
      msg.setIce(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.v1.SignalRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.v1.SignalRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.v1.SignalRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.SignalRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRegistration();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.signaling.v1.Identity.serializeBinaryToWriter
    );
  }
  f = message.getSdp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.signaling.v1.SdpExchange.serializeBinaryToWriter
    );
  }
  f = message.getIce();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.signaling.v1.IceCandidate.serializeBinaryToWriter
    );
  }
};


/**
 * optional Identity registration = 1;
 * @return {?proto.signaling.v1.Identity}
 */
proto.signaling.v1.SignalRequest.prototype.getRegistration = function() {
  return /** @type{?proto.signaling.v1.Identity} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.Identity, 1));
};


/**
 * @param {?proto.signaling.v1.Identity|undefined} value
 * @return {!proto.signaling.v1.SignalRequest} returns this
*/
proto.signaling.v1.SignalRequest.prototype.setRegistration = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.signaling.v1.SignalRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalRequest} returns this
 */
proto.signaling.v1.SignalRequest.prototype.clearRegistration = function() {
  return this.setRegistration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalRequest.prototype.hasRegistration = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SdpExchange sdp = 2;
 * @return {?proto.signaling.v1.SdpExchange}
 */
proto.signaling.v1.SignalRequest.prototype.getSdp = function() {
  return /** @type{?proto.signaling.v1.SdpExchange} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.SdpExchange, 2));
};


/**
 * @param {?proto.signaling.v1.SdpExchange|undefined} value
 * @return {!proto.signaling.v1.SignalRequest} returns this
*/
proto.signaling.v1.SignalRequest.prototype.setSdp = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.signaling.v1.SignalRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalRequest} returns this
 */
proto.signaling.v1.SignalRequest.prototype.clearSdp = function() {
  return this.setSdp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalRequest.prototype.hasSdp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional IceCandidate ice = 3;
 * @return {?proto.signaling.v1.IceCandidate}
 */
proto.signaling.v1.SignalRequest.prototype.getIce = function() {
  return /** @type{?proto.signaling.v1.IceCandidate} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.IceCandidate, 3));
};


/**
 * @param {?proto.signaling.v1.IceCandidate|undefined} value
 * @return {!proto.signaling.v1.SignalRequest} returns this
*/
proto.signaling.v1.SignalRequest.prototype.setIce = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.signaling.v1.SignalRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalRequest} returns this
 */
proto.signaling.v1.SignalRequest.prototype.clearIce = function() {
  return this.setIce(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalRequest.prototype.hasIce = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.signaling.v1.SignalResponse.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.signaling.v1.SignalResponse.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  IDENTITY: 1,
  SDP: 2,
  ICE: 3,
  ERROR: 4
};

/**
 * @return {proto.signaling.v1.SignalResponse.PayloadCase}
 */
proto.signaling.v1.SignalResponse.prototype.getPayloadCase = function() {
  return /** @type {proto.signaling.v1.SignalResponse.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.signaling.v1.SignalResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.v1.SignalResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.v1.SignalResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.v1.SignalResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.SignalResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    identity: (f = msg.getIdentity()) && proto.signaling.v1.Identity.toObject(includeInstance, f),
    sdp: (f = msg.getSdp()) && proto.signaling.v1.SdpExchange.toObject(includeInstance, f),
    ice: (f = msg.getIce()) && proto.signaling.v1.IceCandidate.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.signaling.v1.Error.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.v1.SignalResponse}
 */
proto.signaling.v1.SignalResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.v1.SignalResponse;
  return proto.signaling.v1.SignalResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.v1.SignalResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.v1.SignalResponse}
 */
proto.signaling.v1.SignalResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.signaling.v1.Identity;
      reader.readMessage(value,proto.signaling.v1.Identity.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    case 2:
      var value = new proto.signaling.v1.SdpExchange;
      reader.readMessage(value,proto.signaling.v1.SdpExchange.deserializeBinaryFromReader);
      msg.setSdp(value);
      break;
    case 3:
      var value = new proto.signaling.v1.IceCandidate;
      reader.readMessage(value,proto.signaling.v1.IceCandidate.deserializeBinaryFromReader);
      msg.setIce(value);
      break;
    case 4:
      var value = new proto.signaling.v1.Error;
      reader.readMessage(value,proto.signaling.v1.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.v1.SignalResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.v1.SignalResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.v1.SignalResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.SignalResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.signaling.v1.Identity.serializeBinaryToWriter
    );
  }
  f = message.getSdp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.signaling.v1.SdpExchange.serializeBinaryToWriter
    );
  }
  f = message.getIce();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.signaling.v1.IceCandidate.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.signaling.v1.Error.serializeBinaryToWriter
    );
  }
};


/**
 * optional Identity identity = 1;
 * @return {?proto.signaling.v1.Identity}
 */
proto.signaling.v1.SignalResponse.prototype.getIdentity = function() {
  return /** @type{?proto.signaling.v1.Identity} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.Identity, 1));
};


/**
 * @param {?proto.signaling.v1.Identity|undefined} value
 * @return {!proto.signaling.v1.SignalResponse} returns this
*/
proto.signaling.v1.SignalResponse.prototype.setIdentity = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.signaling.v1.SignalResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalResponse} returns this
 */
proto.signaling.v1.SignalResponse.prototype.clearIdentity = function() {
  return this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalResponse.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SdpExchange sdp = 2;
 * @return {?proto.signaling.v1.SdpExchange}
 */
proto.signaling.v1.SignalResponse.prototype.getSdp = function() {
  return /** @type{?proto.signaling.v1.SdpExchange} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.SdpExchange, 2));
};


/**
 * @param {?proto.signaling.v1.SdpExchange|undefined} value
 * @return {!proto.signaling.v1.SignalResponse} returns this
*/
proto.signaling.v1.SignalResponse.prototype.setSdp = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.signaling.v1.SignalResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalResponse} returns this
 */
proto.signaling.v1.SignalResponse.prototype.clearSdp = function() {
  return this.setSdp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalResponse.prototype.hasSdp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional IceCandidate ice = 3;
 * @return {?proto.signaling.v1.IceCandidate}
 */
proto.signaling.v1.SignalResponse.prototype.getIce = function() {
  return /** @type{?proto.signaling.v1.IceCandidate} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.IceCandidate, 3));
};


/**
 * @param {?proto.signaling.v1.IceCandidate|undefined} value
 * @return {!proto.signaling.v1.SignalResponse} returns this
*/
proto.signaling.v1.SignalResponse.prototype.setIce = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.signaling.v1.SignalResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalResponse} returns this
 */
proto.signaling.v1.SignalResponse.prototype.clearIce = function() {
  return this.setIce(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalResponse.prototype.hasIce = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Error error = 4;
 * @return {?proto.signaling.v1.Error}
 */
proto.signaling.v1.SignalResponse.prototype.getError = function() {
  return /** @type{?proto.signaling.v1.Error} */ (
    jspb.Message.getWrapperField(this, proto.signaling.v1.Error, 4));
};


/**
 * @param {?proto.signaling.v1.Error|undefined} value
 * @return {!proto.signaling.v1.SignalResponse} returns this
*/
proto.signaling.v1.SignalResponse.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.signaling.v1.SignalResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.v1.SignalResponse} returns this
 */
proto.signaling.v1.SignalResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.v1.SignalResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.v1.Identity.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.v1.Identity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.v1.Identity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.Identity.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    publicKey: msg.getPublicKey_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.v1.Identity}
 */
proto.signaling.v1.Identity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.v1.Identity;
  return proto.signaling.v1.Identity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.v1.Identity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.v1.Identity}
 */
proto.signaling.v1.Identity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPublicKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.v1.Identity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.v1.Identity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.v1.Identity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.Identity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPublicKey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.signaling.v1.Identity.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.Identity} returns this
 */
proto.signaling.v1.Identity.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes public_key = 2;
 * @return {!(string|Uint8Array)}
 */
proto.signaling.v1.Identity.prototype.getPublicKey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes public_key = 2;
 * This is a type-conversion wrapper around `getPublicKey()`
 * @return {string}
 */
proto.signaling.v1.Identity.prototype.getPublicKey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPublicKey()));
};


/**
 * optional bytes public_key = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPublicKey()`
 * @return {!Uint8Array}
 */
proto.signaling.v1.Identity.prototype.getPublicKey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPublicKey()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.signaling.v1.Identity} returns this
 */
proto.signaling.v1.Identity.prototype.setPublicKey = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.v1.SdpExchange.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.v1.SdpExchange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.v1.SdpExchange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.SdpExchange.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sdp: jspb.Message.getFieldWithDefault(msg, 2, ""),
    targetUuid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.v1.SdpExchange}
 */
proto.signaling.v1.SdpExchange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.v1.SdpExchange;
  return proto.signaling.v1.SdpExchange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.v1.SdpExchange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.v1.SdpExchange}
 */
proto.signaling.v1.SdpExchange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.signaling.v1.SdpExchange.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSdp(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.v1.SdpExchange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.v1.SdpExchange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.v1.SdpExchange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.SdpExchange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSdp();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTargetUuid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.signaling.v1.SdpExchange.Type = {
  TYPE_UNSPECIFIED: 0,
  TYPE_OFFER: 1,
  TYPE_ANSWER: 2,
  TYPE_PRANSWER: 3,
  TYPE_ROLLBACK: 4
};

/**
 * optional Type type = 1;
 * @return {!proto.signaling.v1.SdpExchange.Type}
 */
proto.signaling.v1.SdpExchange.prototype.getType = function() {
  return /** @type {!proto.signaling.v1.SdpExchange.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.signaling.v1.SdpExchange.Type} value
 * @return {!proto.signaling.v1.SdpExchange} returns this
 */
proto.signaling.v1.SdpExchange.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string sdp = 2;
 * @return {string}
 */
proto.signaling.v1.SdpExchange.prototype.getSdp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.SdpExchange} returns this
 */
proto.signaling.v1.SdpExchange.prototype.setSdp = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string target_uuid = 3;
 * @return {string}
 */
proto.signaling.v1.SdpExchange.prototype.getTargetUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.SdpExchange} returns this
 */
proto.signaling.v1.SdpExchange.prototype.setTargetUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.v1.IceCandidate.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.v1.IceCandidate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.v1.IceCandidate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.IceCandidate.toObject = function(includeInstance, msg) {
  var f, obj = {
    candidate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sdpMid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sdpMLineIndex: jspb.Message.getFieldWithDefault(msg, 3, 0),
    usernameFragment: jspb.Message.getFieldWithDefault(msg, 4, ""),
    targetUuid: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.v1.IceCandidate}
 */
proto.signaling.v1.IceCandidate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.v1.IceCandidate;
  return proto.signaling.v1.IceCandidate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.v1.IceCandidate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.v1.IceCandidate}
 */
proto.signaling.v1.IceCandidate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCandidate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSdpMid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSdpMLineIndex(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsernameFragment(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.v1.IceCandidate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.v1.IceCandidate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.v1.IceCandidate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.IceCandidate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCandidate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSdpMid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSdpMLineIndex();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getUsernameFragment();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTargetUuid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string candidate = 1;
 * @return {string}
 */
proto.signaling.v1.IceCandidate.prototype.getCandidate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.IceCandidate} returns this
 */
proto.signaling.v1.IceCandidate.prototype.setCandidate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sdp_mid = 2;
 * @return {string}
 */
proto.signaling.v1.IceCandidate.prototype.getSdpMid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.IceCandidate} returns this
 */
proto.signaling.v1.IceCandidate.prototype.setSdpMid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 sdp_m_line_index = 3;
 * @return {number}
 */
proto.signaling.v1.IceCandidate.prototype.getSdpMLineIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.signaling.v1.IceCandidate} returns this
 */
proto.signaling.v1.IceCandidate.prototype.setSdpMLineIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string username_fragment = 4;
 * @return {string}
 */
proto.signaling.v1.IceCandidate.prototype.getUsernameFragment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.IceCandidate} returns this
 */
proto.signaling.v1.IceCandidate.prototype.setUsernameFragment = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string target_uuid = 5;
 * @return {string}
 */
proto.signaling.v1.IceCandidate.prototype.getTargetUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.IceCandidate} returns this
 */
proto.signaling.v1.IceCandidate.prototype.setTargetUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.v1.Error.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.v1.Error.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.v1.Error} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.Error.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.v1.Error}
 */
proto.signaling.v1.Error.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.v1.Error;
  return proto.signaling.v1.Error.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.v1.Error} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.v1.Error}
 */
proto.signaling.v1.Error.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.v1.Error.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.v1.Error.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.v1.Error} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.v1.Error.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 code = 1;
 * @return {number}
 */
proto.signaling.v1.Error.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.signaling.v1.Error} returns this
 */
proto.signaling.v1.Error.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.signaling.v1.Error.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.signaling.v1.Error} returns this
 */
proto.signaling.v1.Error.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.signaling.v1);
