// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: proto/v1/signaling.proto

package signalingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SdpExchange_Type int32

const (
	SdpExchange_TYPE_UNSPECIFIED SdpExchange_Type = 0
	SdpExchange_TYPE_OFFER       SdpExchange_Type = 1
	SdpExchange_TYPE_ANSWER      SdpExchange_Type = 2
	SdpExchange_TYPE_PRANSWER    SdpExchange_Type = 3
	SdpExchange_TYPE_ROLLBACK    SdpExchange_Type = 4
)

// Enum value maps for SdpExchange_Type.
var (
	SdpExchange_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_OFFER",
		2: "TYPE_ANSWER",
		3: "TYPE_PRANSWER",
		4: "TYPE_ROLLBACK",
	}
	SdpExchange_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_OFFER":       1,
		"TYPE_ANSWER":      2,
		"TYPE_PRANSWER":    3,
		"TYPE_ROLLBACK":    4,
	}
)

func (x SdpExchange_Type) Enum() *SdpExchange_Type {
	p := new(SdpExchange_Type)
	*p = x
	return p
}

func (x SdpExchange_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdpExchange_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_signaling_proto_enumTypes[0].Descriptor()
}

func (SdpExchange_Type) Type() protoreflect.EnumType {
	return &file_proto_v1_signaling_proto_enumTypes[0]
}

func (x SdpExchange_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdpExchange_Type.Descriptor instead.
func (SdpExchange_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{3, 0}
}

// SignalRequest is a message sent from the client to the server.
type SignalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*SignalRequest_Registration
	//	*SignalRequest_Sdp
	//	*SignalRequest_Ice
	Payload isSignalRequest_Payload `protobuf_oneof:"payload"`
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_signaling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_signaling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{0}
}

func (m *SignalRequest) GetPayload() isSignalRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SignalRequest) GetRegistration() *Identity {
	if x, ok := x.GetPayload().(*SignalRequest_Registration); ok {
		return x.Registration
	}
	return nil
}

func (x *SignalRequest) GetSdp() *SdpExchange {
	if x, ok := x.GetPayload().(*SignalRequest_Sdp); ok {
		return x.Sdp
	}
	return nil
}

func (x *SignalRequest) GetIce() *IceCandidate {
	if x, ok := x.GetPayload().(*SignalRequest_Ice); ok {
		return x.Ice
	}
	return nil
}

type isSignalRequest_Payload interface {
	isSignalRequest_Payload()
}

type SignalRequest_Registration struct {
	Registration *Identity `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type SignalRequest_Sdp struct {
	Sdp *SdpExchange `protobuf:"bytes,2,opt,name=sdp,proto3,oneof"`
}

type SignalRequest_Ice struct {
	Ice *IceCandidate `protobuf:"bytes,3,opt,name=ice,proto3,oneof"`
}

func (*SignalRequest_Registration) isSignalRequest_Payload() {}

func (*SignalRequest_Sdp) isSignalRequest_Payload() {}

func (*SignalRequest_Ice) isSignalRequest_Payload() {}

// SignalResponse is a message sent from the server to the client.
type SignalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*SignalResponse_Identity
	//	*SignalResponse_Sdp
	//	*SignalResponse_Ice
	//	*SignalResponse_Error
	Payload isSignalResponse_Payload `protobuf_oneof:"payload"`
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_signaling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_signaling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{1}
}

func (m *SignalResponse) GetPayload() isSignalResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SignalResponse) GetIdentity() *Identity {
	if x, ok := x.GetPayload().(*SignalResponse_Identity); ok {
		return x.Identity
	}
	return nil
}

func (x *SignalResponse) GetSdp() *SdpExchange {
	if x, ok := x.GetPayload().(*SignalResponse_Sdp); ok {
		return x.Sdp
	}
	return nil
}

func (x *SignalResponse) GetIce() *IceCandidate {
	if x, ok := x.GetPayload().(*SignalResponse_Ice); ok {
		return x.Ice
	}
	return nil
}

func (x *SignalResponse) GetError() *Error {
	if x, ok := x.GetPayload().(*SignalResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isSignalResponse_Payload interface {
	isSignalResponse_Payload()
}

type SignalResponse_Identity struct {
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3,oneof"`
}

type SignalResponse_Sdp struct {
	Sdp *SdpExchange `protobuf:"bytes,2,opt,name=sdp,proto3,oneof"`
}

type SignalResponse_Ice struct {
	Ice *IceCandidate `protobuf:"bytes,3,opt,name=ice,proto3,oneof"`
}

type SignalResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SignalResponse_Identity) isSignalResponse_Payload() {}

func (*SignalResponse_Sdp) isSignalResponse_Payload() {}

func (*SignalResponse_Ice) isSignalResponse_Payload() {}

func (*SignalResponse_Error) isSignalResponse_Payload() {}

// Identity defines a peer's registration information.
type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_signaling_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_signaling_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *Identity) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Identity) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// SdpExchange handles WebRTC Session Description Protocol (SDP) offers and answers.
type SdpExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       SdpExchange_Type `protobuf:"varint,1,opt,name=type,proto3,enum=signaling.v1.SdpExchange_Type" json:"type,omitempty"`
	Sdp        string           `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	TargetUuid string           `protobuf:"bytes,3,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
}

func (x *SdpExchange) Reset() {
	*x = SdpExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_signaling_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdpExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpExchange) ProtoMessage() {}

func (x *SdpExchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_signaling_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpExchange.ProtoReflect.Descriptor instead.
func (*SdpExchange) Descriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *SdpExchange) GetType() SdpExchange_Type {
	if x != nil {
		return x.Type
	}
	return SdpExchange_TYPE_UNSPECIFIED
}

func (x *SdpExchange) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SdpExchange) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

// IceCandidate represents a WebRTC ICE candidate.
type IceCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate        string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMLineIndex    int32  `protobuf:"varint,3,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	UsernameFragment string `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	TargetUuid       string `protobuf:"bytes,5,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_signaling_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_signaling_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *IceCandidate) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

func (x *IceCandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

func (x *IceCandidate) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

// Error represents a signaling error.
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_signaling_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_signaling_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_v1_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_v1_signaling_proto protoreflect.FileDescriptor

var file_proto_v1_signaling_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0c, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x64, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x2e, 0x0a, 0x03, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x03, 0x69, 0x63, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xdd, 0x01, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x48,
	0x00, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x03, 0x73,
	0x64, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x64, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x2e, 0x0a, 0x03, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x03, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x3d, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0xd9, 0x01, 0x0a, 0x0b, 0x53, 0x64, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1e, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x64, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x63, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f,
	0x46, 0x46, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41,
	0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x52, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x4c, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x04, 0x22, 0xbc, 0x01,
	0x0a, 0x0c, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x64, 0x70, 0x5f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x64, 0x70, 0x4d, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x10, 0x73, 0x64, 0x70, 0x5f, 0x6d, 0x5f, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x73, 0x64, 0x70, 0x4d, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2b,
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x55, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x12, 0x48, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x75, 0x73, 0x68, 0x30, 0x30,
	0x67, 0x69, 0x74, 0x2f, 0x6c, 0x6f, 0x77, 0x6b, 0x65, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x31, 0x3b, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_signaling_proto_rawDescOnce sync.Once
	file_proto_v1_signaling_proto_rawDescData = file_proto_v1_signaling_proto_rawDesc
)

func file_proto_v1_signaling_proto_rawDescGZIP() []byte {
	file_proto_v1_signaling_proto_rawDescOnce.Do(func() {
		file_proto_v1_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_signaling_proto_rawDescData)
	})
	return file_proto_v1_signaling_proto_rawDescData
}

var file_proto_v1_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_signaling_proto_goTypes = []interface{}{
	(SdpExchange_Type)(0),  // 0: signaling.v1.SdpExchange.Type
	(*SignalRequest)(nil),  // 1: signaling.v1.SignalRequest
	(*SignalResponse)(nil), // 2: signaling.v1.SignalResponse
	(*Identity)(nil),       // 3: signaling.v1.Identity
	(*SdpExchange)(nil),    // 4: signaling.v1.SdpExchange
	(*IceCandidate)(nil),   // 5: signaling.v1.IceCandidate
	(*Error)(nil),          // 6: signaling.v1.Error
}
var file_proto_v1_signaling_proto_depIdxs = []int32{
	3, // 0: signaling.v1.SignalRequest.registration:type_name -> signaling.v1.Identity
	4, // 1: signaling.v1.SignalRequest.sdp:type_name -> signaling.v1.SdpExchange
	5, // 2: signaling.v1.SignalRequest.ice:type_name -> signaling.v1.IceCandidate
	3, // 3: signaling.v1.SignalResponse.identity:type_name -> signaling.v1.Identity
	4, // 4: signaling.v1.SignalResponse.sdp:type_name -> signaling.v1.SdpExchange
	5, // 5: signaling.v1.SignalResponse.ice:type_name -> signaling.v1.IceCandidate
	6, // 6: signaling.v1.SignalResponse.error:type_name -> signaling.v1.Error
	0, // 7: signaling.v1.SdpExchange.type:type_name -> signaling.v1.SdpExchange.Type
	1, // 8: signaling.v1.Signaling.Connect:input_type -> signaling.v1.SignalRequest
	2, // 9: signaling.v1.Signaling.Connect:output_type -> signaling.v1.SignalResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_signaling_proto_init() }
func file_proto_v1_signaling_proto_init() {
	if File_proto_v1_signaling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_signaling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_signaling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_signaling_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_signaling_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdpExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_signaling_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceCandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_signaling_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_v1_signaling_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SignalRequest_Registration)(nil),
		(*SignalRequest_Sdp)(nil),
		(*SignalRequest_Ice)(nil),
	}
	file_proto_v1_signaling_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SignalResponse_Identity)(nil),
		(*SignalResponse_Sdp)(nil),
		(*SignalResponse_Ice)(nil),
		(*SignalResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_signaling_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_signaling_proto_goTypes,
		DependencyIndexes: file_proto_v1_signaling_proto_depIdxs,
		EnumInfos:         file_proto_v1_signaling_proto_enumTypes,
		MessageInfos:      file_proto_v1_signaling_proto_msgTypes,
	}.Build()
	File_proto_v1_signaling_proto = out.File
	file_proto_v1_signaling_proto_rawDesc = nil
	file_proto_v1_signaling_proto_goTypes = nil
	file_proto_v1_signaling_proto_depIdxs = nil
}
